# Generated by Django 3.1.7 on 2021-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=200)),
                ('auth_yn', models.BooleanField()),
            ],
            options={
                'db_table': 'auth_category',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
