# Generated by Django 3.1.7 on 2021-06-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionSys', '0002_auto_20210608_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_category',
            name='auth_explain',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
