# Generated by Django 3.1.7 on 2021-06-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionSys', '0003_auth_category_auth_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_category',
            name='auth_path',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
